---
- name: Deploy Maven Artifact (Jenkins User Accessible)
  hosts: local 
  # become: yes # Removed to avoid requiring sudo

  tasks:
    - name: Ensure deployment directory exists
      ansible.builtin.file:
        path: "/var/lib/jenkins/deployment" 
        state: directory
        mode: '0755' 

    - name: Copy the artifact to the deployment directory
      ansible.builtin.copy:
        src: "/var/lib/jenkins/workspace/exp8/target/*.jar"
        dest: "/var/lib/jenkins/deployment/HelloMaven.jar"
        remote_src: yes 
